### ISSUE TITLE
BUG: The way to segment dataset

### ISSUE THREAD

**Issue by pxzhang94** [joelowj/NeuralTest#10]
@joelowj In function prepare_data_sets, it divides the dataset into train and validation sets in this way, not random, it will bring about these two datasets don't have the same distribution. According to the test, in nearly the first 13500, it will successfully generate 10000 positive data, and the last 6500 data are all negative. So it's better to shuffle the dataset before dividing or divide it randomly.

**Comment by joelowj** [comment]
@pxzhang94, proposed this change to fix the issue with the data segmentation fault.
I will push the code, if it is agreeable.

    perm0 = np.arange(len(vectors))
    np.random.shuffle(perm0)
    vectors = vectors[perm0]
    labels = labels[perm0]

**Comment by pxzhang94** [comment]
@joelowj Great!
