### ISSUE TITLE
BUG:The Loss Function

### ISSUE THREAD

**Issue by pxzhang94** [joelowj/NeuralTest#11]
@joelowj About the loss fuction of discriminator and generator, our goal is to judge whether a condition is true or false, not judge whether a picture is real or fake, so unlike the image recognition, our real inputs have both 1 and 0 labels. Therefore, it is not correct to use random labels in loss fuction, we need to use batch_labels in d_loss_real, the input of generator in g_loss, and as for d_loss_fake, advise to use the return of fuction predicate by runing the outputs from generator.

**Comment by joelowj** [comment]
@pxzhang94 , please review the changes.
