### ISSUE TITLE
List Of Predicates to Test

### ISSUE THREAD

**Issue by joelowj** [joelowj/NeuralTest#14]
Hi @pxzhang94 @llmhyy as spoken, please provide me with the list of predicates to test.
I will run all the test on jupyter notebook.

**Comment by pxzhang94** [comment]
I just push the list of predicates we will test. The file in document files has two format xlsx and numbers (they are the same), the predicates I marked in red will test first, I finished write them in function_test.py. It is better to do batch test, so I think we need to restructure your program, I will raise a new issue later.
